name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main", "develop"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main", "develop"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: python:3.10

    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: jpox_test_pw
          POSTGRES_ENGINE: django.db.backends.postgresql
          POSTGRES_DB: postgres
          POSTGRES_USER: jpox_test_user
          POSTGRES_HOST: localhost
    env:
      # postgres://user:password@host:port/database
      DATABASE_URL: "postgres://jpox_test_user:jpox_test_pw@localhost:5432/jpox_test_db"
      POSTGRES_PASSWORD: jpox_test_pw
      POSTGRES_ENGINE: django.db.backends.postgresql
      POSTGRES_DB: postgres
      POSTGRES_USER: jpox_test_user
      POSTGRES_HOST: localhost

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: apt-get install -y libpq-dev

      #      - name: Set up Python
      #        uses: actions/setup-python@v3
      #        with:
      #          python-version: "3.10"
      #          cache: pip
      #          cache-dependency-path: |
      #            requirements/base.txt
      #            requirements/local.txt

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install -r requirements/local.txt

      - name: Run Linters and Checks
        run: |
          pre-commit run --all

      - name: Test with pytest
        run: pytest --ds=config.settings.test --reuse-db
